network:
    version: 2
    ethernets:
        eth0:
            optional: true
            dhcp4: true
    wifis:
        wlan0:
            optional: true
            addresses: [192.168.0.200/24]
            access-points:
                "access-point":
                    password: "password"
            dhcp4: false
